info:
  contact: {}
  description: This API is used to interact with Carbonaut resources
  license:
    name: MIT
    url: https://mit-license.org
  title: Carbonaut API
  version: "0.1"
paths:
  /api/v0.1/init:
    post:
      description: Initialize carbonaut to be fully functional
      responses:
        "200":
          description: OK
          schema:
            type: string
  /api/v0.1/status/:
    get:
      description: Carbonaut Status Endpoint
      responses:
        "200":
          description: OK
          schema:
            type: string
swagger: "2.0"
